"""Command-line interface for airisk."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer
import yaml

from . import __version__
from .chart import render_maturity_radar
from .loaders import (
    DataError,
    Paths,
    load_assessment,
    load_eu_ai_act,
    load_inventory,
    load_nist_framework,
    load_org,
)
from .report import build_context, write_reports
from .scoring import score_nist

app = typer.Typer(
    add_completion=False,
    help="AI governance risk assessment scoring + report generator (synthetic FakeOrg demo).",
)

RootOpt = Annotated[
    Path | None,
    typer.Option("--root", "-r", help="Project root containing data/ and frameworks/."),
]

CHART_FILENAME = "maturity-chart.png"


def _fail(message: str) -> None:
    typer.secho(message, fg=typer.colors.RED, err=True)
    raise typer.Exit(code=1)


@app.command()
def version() -> None:
    """Print the airisk version."""
    typer.echo(f"airisk {__version__}")


@app.command()
def validate(root: RootOpt = None) -> None:
    """Load and schema-validate every YAML input file."""
    paths = Paths.from_root(root)
    checks = {
        "organization": load_org,
        "ai_inventory": load_inventory,
        "nist_framework": load_nist_framework,
        "eu_ai_act": load_eu_ai_act,
    }
    failed = False
    for name, loader in checks.items():
        try:
            loader(paths)
            typer.secho(f"  ok    {name}", fg=typer.colors.GREEN)
        except DataError as exc:
            failed = True
            typer.secho(f"  FAIL  {name}\n{exc}", fg=typer.colors.RED, err=True)
    # The assessment file is optional until init-assessment has been run.
    if paths.nist_assessment.exists():
        try:
            load_assessment(paths)
            typer.secho("  ok    nist_assessment", fg=typer.colors.GREEN)
        except DataError as exc:
            failed = True
            typer.secho(f"  FAIL  nist_assessment\n{exc}", fg=typer.colors.RED, err=True)
    if failed:
        raise typer.Exit(code=1)
    typer.secho("All inputs valid.", fg=typer.colors.GREEN)


@app.command(name="init-assessment")
def init_assessment(
    root: RootOpt = None,
    force: Annotated[bool, typer.Option("--force", help="Overwrite an existing file.")] = False,
) -> None:
    """Generate a blank control-rating file from the NIST framework catalog."""
    paths = Paths.from_root(root)
    if paths.nist_assessment.exists() and not force:
        _fail(f"{paths.nist_assessment} already exists. Use --force to overwrite.")

    try:
        framework = load_nist_framework(paths)
    except DataError as exc:
        _fail(str(exc))

    ratings = [
        {"id": sub_id, "status": None, "evidence": [], "notes": ""}
        for sub_id in framework.subcategory_ids
    ]
    payload = {
        "meta": {"framework": "NIST AI RMF 1.0", "generated_by": "airisk init-assessment"},
        "ratings": ratings,
    }

    paths.nist_assessment.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# NIST AI RMF control ratings for FakeOrg (SYNTHETIC)\n"
        "# Generated by `airisk init-assessment`. Set each status to one of:\n"
        "#   Met | Partial | Not Met | Not Applicable   (leave null = not assessed)\n"
    )
    paths.nist_assessment.write_text(header + yaml.safe_dump(payload, sort_keys=False))
    typer.secho(
        f"Wrote {len(ratings)} blank ratings to {paths.nist_assessment}", fg=typer.colors.GREEN
    )


@app.command()
def assess(root: RootOpt = None) -> None:
    """Score the assessment and render the scorecard, report, and maturity chart."""
    paths = Paths.from_root(root)
    try:
        org = load_org(paths)
        inventory = load_inventory(paths)
        framework = load_nist_framework(paths)
        eu_ai_act = load_eu_ai_act(paths)
        if not paths.nist_assessment.exists():
            _fail(
                f"No ratings file at {paths.nist_assessment}. "
                "Run `airisk init-assessment` first."
            )
        assessment = load_assessment(paths)
    except DataError as exc:
        _fail(str(exc))

    score = score_nist(framework, assessment.status_by_id())

    chart_path = paths.reports_dir / CHART_FILENAME
    chart_title = f"{org.organization.name} — AI Governance Maturity"
    render_maturity_radar(score, chart_path, title=chart_title)

    context = build_context(org, inventory, score, eu_ai_act, CHART_FILENAME)
    written = write_reports(paths.reports_dir, context)

    overall = score.overall.maturity_pct
    overall_str = "not assessed" if overall is None else f"{overall:.1f}%"
    typer.secho(
        f"Assessed {score.overall.assessed}/{score.overall.total} subcategories "
        f"(overall maturity: {overall_str}).",
        fg=typer.colors.GREEN,
    )
    for path in (chart_path, *written):
        typer.echo(f"  wrote {path}")


def main() -> None:  # console-script entry point
    app()


if __name__ == "__main__":
    main()
